covermymeds/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('admin/', admin.site.urls),
    path('crud/', include('crud.urls')),    
    path('', RedirectView.as_view(url="/crud/")),
]

crud/urls.py
from django.urls import path

from . import views

app_name = 'crud'
urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search'),
    path('create/', views.create, name='create'),
    path('create/<int:id>/<int:success>', views.create, name='create'),
    path('create/<int:id>', views.create, name='create'),
]

crud/models.py
from django.db import models

# Create your models here.
class Person(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)
    date = models.DateField()
    number = models.IntegerField()

crud/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Person

# Create your views here.
@login_required
def index(request):
    return render(request, 'crud/index.html')

@login_required
def search(request):
    if request.GET and request.GET["search_str"]:
        people = Person.objects.filter(name__icontains=request.GET["search_str"])[:5]
    else:
        people = Person.objects.all()[:5]
    return render(request, 'crud/search.html', context={"people" : people})

@login_required
def create(request, id=None, success=None):
    context = {}
    if request.POST:
        name = request.POST["id_name"]
        date = request.POST["id_date"]
        number = request.POST["id_number"]
        submit = request.POST["btn_submit"]
        _id = request.POST["id_person"]
        if submit == "Delete":
            Person.objects.get(id=_id).delete()
            print("deleting")
            return redirect('crud:create')
        if _id and submit != "Delete":
            p = Person.objects.get(id=_id)
            p.name = name
            p.date = date
            p.number = number
            p.save()
            return redirect('crud:create', id=p.id, success=1)
        p = Person(name=name, date=date, number=number)
        p.save()
        return redirect('crud:create', id=p.id, success=1)
    elif id:
        p = get_object_or_404(Person, id=id)
        context["Person"] = p
        if success:
            context['success'] = True
    return render(request, 'crud/create.html', context)

crud/templates/crud/create.html
{% extends 'global/global.html' %}

{% block content %}
    {% load static %}
    <script type="text/javascript" src="{% static 'crud/create.js' %}"></script>
    <h1>{{Person|yesno:"Edit,Create"}}</h1>
    {% if success %}
    <span class="success bg-success">Record Created Successfully!</span>
    {% endif %}
    <form style="width: 50%;" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Name</label>
            <input value="{{Person.name}}" type="text" class="form-control" id="id_name" name="id_name" required>
        </div>
        <div class="form-group">
            <label for="id_date">Date</label>
            <input value="{{Person.date|date:'Y-m-d'}}" type="date" class="form-control" id="id_date" name="id_date" required>
        </div>
        <div class="form-group">
            <label for="id_num">Number</label>
            <input value="{{Person.number}}" type="number" class="form-control" id="id_number" name="id_number" required>
        </div>
        <div class="form-group">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <button type="submit" value="Update" name="btn_submit" id="btn_submit" class="btn btn-success">{{Person|yesno:"Update,Create"}}</button>
                    {% if Person %}
                    <button type="submit" value="Delete" class="btn btn-danger" name="btn_submit" id="btn_delete">Delete</button>
                    {% endif %}
                </div>
            </div>
        </div>
        
        <input type="hidden" value="{{Person.id}}" name="id_person" id="id_person">
    </form>
{% endblock %}

crud/templates/crud/index.html
{% extends 'global/global.html' %}

{% block content %}
    <h1>Welcome to CRUD!</h1>
    <h3>Navigate the site using the links above</h3>
{% endblock %}

crud/templates/crud/search.html
{% extends 'global/global.html' %}

{% block content %}
    {% load static %}
    <script type="text/javascript" src="{% static 'crud/search.js' %}"></script>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Search</h3>
            </div>
        </div>
        <form method="GET">
            <div class="col-lg-4 col-lg-offset-4">
                <input type="search" id="search_str" name="search_str" value="" class="form-control" placeholder="Search by name">
            </div>
            <input type="submit" id="btn_submit" name="btn_submit" value="Search" class="btn btn-primary">
        </form>
        <div class="row">
            <div class="col-lg-12">
                <table class="table" id="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Date</th>
                            <th>Number</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for person in people %}
                        <tr>
                            <td><a href="{% url 'crud:create' id=person.id %}">{{person.name}}</a></td>
                            <td>{{person.date}}</td>
                            <td>{{person.number}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <hr>
            </div>
        </div>
    </div>
{% endblock %}

templates/global/global.html
<header>
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.0.0.min.js" integrity="sha256-JmvOoLtYsmqlsWxa7mDSLMwa6dZ9rrIdtrrVYRnDRH0=" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'global/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <div>
        <a href="{% url 'crud:index' %}">Home</a>
        <a href="{% url 'crud:search' %}">Search</a>
        <a href="{% url 'crud:create' %}">Create</a>
    </div>
</header>
<body>
    <div class="body">
        {% block content %}{% endblock %}
    </div>
</body>
<footer>
    <span>Created by Luke Shays</span>
</footer>